"""Emit normative tables and golden vectors as source, one file per language.

Avoids a JSON dependency in Java, Rust and Swift, and makes each implementation
standalone. Regenerate rather than hand-edit the outputs.
"""
import json, os, unicodedata as ud

T = json.load(open("tables.json"))
V = json.load(open("vectors.json"))
os.makedirs("impl", exist_ok=True)

def spans(name):
    out = []
    for s in T[name]:
        lo, _, hi = s.partition("-")
        out.append((int(lo, 16), int(hi or lo, 16)))
    return out

# Complete Unicode Default Case Folding. A per-character table, so no
# implementation depends on its runtime's case mapping — Go's strings.ToLower
# applies SIMPLE mapping and turns U+0130 into "i" where full folding gives
# "i" + U+0307. §5.2, Appendix B.6.
FOLDGAP = {}
for cp in range(0x110000):
    c = chr(cp)
    if ud.category(c) == "Cn":
        continue
    if c.casefold() != c:
        FOLDGAP[cp] = c.casefold()

# every Unicode decimal digit -> its ASCII equivalent (§6.2)
DIGITS = {}
for cp in range(0x110000):
    d = ud.decimal(chr(cp), None)
    if d is not None:
        DIGITS[cp] = str(d)

# ---------------------------------------------------------------- escaping
# Java processes \uXXXX escapes in the lexer, BEFORE parsing, so \u000A becomes a
# real newline and breaks the string literal. Line terminators and the quoting
# characters must use conventional escapes instead.
_JAVA_ESC = {0x0A: "\\n", 0x0D: "\\r", 0x09: "\\t", 0x08: "\\b",
             0x0C: "\\f", 0x22: '\\"', 0x5C: "\\\\"}

def esc_java(s):
    o = []
    for ch in s:
        cp = ord(ch)
        if cp in _JAVA_ESC:
            o.append(_JAVA_ESC[cp])
        elif cp > 0xFFFF:
            cp -= 0x10000
            o.append(f"\\u{0xD800 + (cp >> 10):04X}\\u{0xDC00 + (cp & 0x3FF):04X}")
        elif 0x20 <= cp < 0x7F and ch not in '"\\':
            o.append(ch)
        else:
            o.append(f"\\u{cp:04X}")
    return '"' + "".join(o) + '"'

def esc_brace(s):          # JS, Rust, Swift
    o = []
    for ch in s:
        cp = ord(ch)
        if 0x20 <= cp < 0x7F and ch not in '"\\':
            o.append(ch)
        else:
            o.append(f"\\u{{{cp:X}}}")
    return '"' + "".join(o) + '"'

def esc_go(s):
    o = []
    for ch in s:
        cp = ord(ch)
        if 0x20 <= cp < 0x7F and ch not in '"\\':
            o.append(ch)
        else:
            o.append(f"\\U{cp:08X}")
    return '"' + "".join(o) + '"'

ESC = {"java": esc_java, "js": esc_brace, "rust": esc_brace,
       "swift": esc_brace, "go": esc_go}

def rows(lang):
    """Vectors flattened to (section, label, a, b, c) with everything stringly typed."""
    out = []
    for label, src, want in V["normalize"]:
        out.append(("normalize", label, src, want, ""))
    for label, a, want in V["generate"]:
        lang_, who, role, scope, flags, priv = a
        who = "\x00ME" if who is None else who
        out.append(("generate", label, "\x01".join([lang_, who, role, scope, flags, priv]), want, ""))
    for label, a in V["reject"]:
        lang_, who, role, scope, flags, priv = a
        who = "\x00ME" if who is None else who
        out.append(("reject", label, "\x01".join([lang_, who, role, scope, flags, priv]), "", ""))
    for label, src, want in V["parse"]:
        out.append(("parse", label, src, "\x01".join(want), ""))
    for label, alias, query, want in V["match"]:
        out.append(("match", label, alias, query, "true" if want else "false"))
    for label, corpus, query, want in V["search"]:
        out.append(("search", label, "\x01".join(corpus), query, "\x01".join(want)))
    return out

def emit(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w").write(text)
    print(f"  {path:44} {len(text.splitlines()):>5} lines")

# ---------------------------------------------------------------- per language
def ranges_lit(name, fmt):
    return ", ".join(fmt(lo, hi) for lo, hi in spans(name))

print("generating:")

# ---- JavaScript
js = ["// Generated by gencode.py. Do not edit.\n"]
for n in ("split", "virama", "arabic"):
    js.append(f"export const {n.upper()} = [" +
              ", ".join(f"[0x{lo:X},0x{hi:X}]" for lo, hi in spans(n)) + "];")
js.append("export const FOLDGAP = new Map([" +
          ",".join(f"[0x{k:X},{esc_brace(v)}]" for k, v in FOLDGAP.items()) + "]);")
js.append("export const DIGITS = new Map([" +
          ",".join(f"[0x{k:X},{esc_brace(v)}]" for k, v in DIGITS.items()) + "]);")
js.append("export const VECTORS = [")
for r in rows("js"):
    js.append("  [" + ",".join(esc_brace(x) for x in r) + "],")
js.append("];")
emit("impl/js/data.mjs", "\n".join(js) + "\n")

# ---- Go
go = ["// Generated by gencode.py. Do not edit.", "package coia", ""]
for n in ("split", "virama", "arabic"):
    go.append(f"var {n.title()} = [][2]rune{{" +
              ", ".join(f"{{0x{lo:X},0x{hi:X}}}" for lo, hi in spans(n)) + "}")
go.append("var Foldgap = map[rune]string{" +
          ", ".join(f"0x{k:X}: {esc_go(v)}" for k, v in FOLDGAP.items()) + "}")
go.append("var Digits = map[rune]rune{" +
          ", ".join(f"0x{k:X}: '{v}'" for k, v in DIGITS.items()) + "}")
go.append("var Vectors = [][5]string{")
for r in rows("go"):
    go.append("  {" + ", ".join(esc_go(x) for x in r) + "},")
go.append("}")
emit("impl/go/data.go", "\n".join(go) + "\n")

# ---- Java
ja = ["// Generated by gencode.py. Do not edit.", "final class Data {"]
for n in ("split", "virama", "arabic"):
    ja.append(f"  static final int[][] {n.upper()} = {{" +
              ", ".join(f"{{0x{lo:X},0x{hi:X}}}" for lo, hi in spans(n)) + "};")
ja.append("  static final String[][] FOLDGAP = {" +
          ", ".join(f"{{{esc_java(chr(k))},{esc_java(v)}}}" for k, v in FOLDGAP.items()) + "};")
ja.append("  static final int[][] DIGITS = {" +
          ", ".join(f"{{0x{k:X},{ord(v)}}}" for k, v in DIGITS.items()) + "};")
ja.append("  static final String[][] VECTORS = {")
for r in rows("java"):
    ja.append("    {" + ",".join(esc_java(x) for x in r) + "},")
ja.append("  };\n}")
emit("impl/java/Data.java", "\n".join(ja) + "\n")

# ---- Rust
rs = ["// Generated by gencode.py. Do not edit.", ""]
for n in ("split", "virama", "arabic"):
    rs.append(f"pub const {n.upper()}: &[(u32,u32)] = &[" +
              ", ".join(f"(0x{lo:X},0x{hi:X})" for lo, hi in spans(n)) + "];")
rs.append("pub const FOLDGAP: &[(u32,&str)] = &[" +
          ", ".join(f"(0x{k:X},{esc_brace(v)})" for k, v in FOLDGAP.items()) + "];")
rs.append("pub const DIGITS: &[(u32,char)] = &[" +
          ", ".join(f"(0x{k:X},'{v}')" for k, v in DIGITS.items()) + "];")
rs.append("pub const VECTORS: &[[&str;5]] = &[")
for r in rows("rust"):
    rs.append("  [" + ",".join(esc_brace(x) for x in r) + "],")
rs.append("];")
emit("impl/rust/src/data.rs", "\n".join(rs) + "\n")

# ---- Swift
sw = ["// Generated by gencode.py. Do not edit.", ""]
for n in ("split", "virama", "arabic"):
    sw.append(f"let {n.upper()}: [(UInt32,UInt32)] = [" +
              ", ".join(f"(0x{lo:X},0x{hi:X})" for lo, hi in spans(n)) + "]")
sw.append("let FOLDGAP: [UInt32:String] = [" +
          ", ".join(f"0x{k:X}:{esc_brace(v)}" for k, v in FOLDGAP.items()) + "]")
sw.append("let DIGITS: [UInt32:Character] = [" +
          ", ".join(f"0x{k:X}:\"{v}\"" for k, v in DIGITS.items()) + "]")
sw.append("let VECTORS: [[String]] = [")
for r in rows("swift"):
    sw.append("  [" + ",".join(esc_brace(x) for x in r) + "],")
sw.append("]")
emit("impl/swift/Data.swift", "\n".join(sw) + "\n")

print(f"\nFOLDGAP {len(FOLDGAP)}   DIGITS {len(DIGITS)}   vectors {len(rows('js'))}")
